version: '3.1'

volumes:
  pg_avoid:

services:
  avoid_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: i0907r
      POSTGRES_DB: postgres
    volumes:
      - pg_avoid:/var/lib/postgresql/data
      - ./uploads:/app/uploads
    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - avoid_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://avoid_db:5432/postgres"
      JAVA_OPTIONS: "-Xmx512M"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app